spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: oumaima
    password: ecom
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: ecommerce_yt
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
    default-schema: ecommerce_yt
    contexts: local
    user: oumaima
    password: ecom
    
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG
    com.example.ecom: DEBUG