services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=oumaima
      - POSTGRES_PASSWORD=ecom
      - POSTGRES_DB=ecom
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oumaima -d ecom"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: